### ISSUE TITLE
Everything messing on first start (and next too)

### ISSUE THREAD

**Issue by ogonkov** [njdelima/snapGallery#1]
Chrome 47.0.2526.106 (64-bit). Starts working only when changing columns to 4 and then back to 3.
![snap_gallery_bug](https://cloud.githubusercontent.com/assets/1091927/13553030/23cd9758-e38b-11e5-9396-b992619ca550.png)

**Comment by njdelima** [comment]
plugin was being called before the images were loaded

Should be fixed now...
